// src/components/homepage/JourneyPoint.tsx
import Link from "next/link";

interface Props {
  text?: string;
  year?: number;
  creation?: string;
  creationText?: string;
  creationUrl?: string;
  creationPrefix?: string;
  creationSuffix?: string;
  lineHeight?: number;
  skipPoint?: boolean;
}

export default function JourneyPoint({
  text = "",
  year = -1,
  creation = "",
  creationText = "",
  creationUrl = "",
  creationPrefix = "",
  creationSuffix = "",
  lineHeight = 500,
  skipPoint = false,
}: Props) {
  return (
    <div className="xs:w-[90%] flex flex-col items-center justify-center animation-150 mt-[10px] w-full">
      {year != -1 && (
        <h1 className="xs:text-base border-2 border-foreground/10 rounded-full p-0.5 pl-2 pr-2 font-black text-lg mb-1 tracking-tight">
          {year}
        </h1>
      )}

      {creation ? (
        <h1 className="xs:text-base font-medium text-lg mb-1 tracking-tight">
          {text} {creationText ? creationText : "Created"}{" "}
          {creationPrefix ? `${creationPrefix} ` : ""}
          <Link href={creationUrl} target="_blank">
            {creation}
          </Link>{" "}
          {creationSuffix ? `${creationSuffix} ` : ""}
        </h1>
      ) : (
        <h1 className="xs:text-base font-medium text-lg mb-1 tracking-tight">
          {text}
        </h1>
      )}

      {!skipPoint && (
        <div className="xs:w-[20px] xs:h-[20px] w-[25px] h-[25px] rounded-full border-2 border-[hsl(var(--foreground))]" />
      )}

      <div
        className={`bg-[hsl(var(--foreground))] w-[2px] h-[200px]`}
        style={{
          height: lineHeight,
        }}
      />
    </div>
  );
}

// src/lib/journey/JourneyPoint.svelte
<script lang="ts">
    import Saos from 'saos';

    export let text = '';
    export let lineHeight = 500;
    export let creation = '';
    export let creationText = '';
    export let creationUrl = '';
    export let creationPrefix = '';
    export let creationSuffix = '';
    export let skipPoint = false;
</script>

<Saos animation={'move-up .5s cubic-bezier(0.8, 0.9, 0.9, 0.9) forwards'}>
    <div
        class="flex flex-col items-center justify-center animation-150 mt-[10px] w-full"
    >
        {#if creation}
            <h1
                class="mobile:text-base text-2xl text-center text-white font-medium select-none mb-2"
            >
                {text}
                {creationText ? creationText : 'Created'}
                {creationPrefix ? `${creationPrefix} ` : ''}<a
                    href={creationUrl}
                    target="_blank">{creation}</a
                >
                {creationSuffix ? `${creationSuffix} ` : ''}
            </h1>
        {:else}
            <h1
                class="mobile:text-base text-2xl text-center text-white font-medium select-none mb-2"
            >
                {text}
            </h1>
        {/if}

        {#if !skipPoint}
            <div
                class="mobile:w-[20px] mobile:h-[20px] point w-[25px] h-[25px] border-2 border-point mb-2 rounded-full"
            />
        {/if}

        <div
            class="line w-[1.5px] h-[200px] bg-line"
            style={`height: ${lineHeight}px;`}
        />
    </div>
</Saos>

<style>
    @keyframes -global-move-up {
        0% {
            opacity: 0;
        }
    }
</style>
